const buttonFilled: Record<string, Record<string, string>> = {
  white: {
    backgroud: 'bg-white',
    color: 'text-blue-gray-900',
    shadow: 'shadow-md shadow-blue-gray-500/40',
    hover: 'hover:shadow-lg hover:shadow-blue-gray-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  'blue-gray': {
    color: 'text-white',
    backgroud: 'bg-blue-gray-500',
    shadow: 'shadow-md shadow-blue-gray-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-blue-gray-500/40',
  },
  gray: {
    color: 'text-white',
    backgroud: 'bg-gray-500',
    shadow: 'shadow-md shadow-gray-500/20',
    hover: 'hover:shadow-lg hover:shadow-gray-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  brown: {
    color: 'text-white',
    backgroud: 'bg-brown-500',
    shadow: 'shadow-md shadow-brown-500/20',
    hover: 'hover:shadow-lg hover:shadow-brown-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  'deep-orange': {
    color: 'text-white',
    backgroud: 'bg-deep-orange-500',
    shadow: 'shadow-md shadow-deep-orange-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-deep-orange-500/40',
  },
  orange: {
    color: 'text-white',
    backgroud: 'bg-orange-500',
    shadow: 'shadow-md shadow-orange-500/20',
    hover: 'hover:shadow-lg hover:shadow-orange-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  amber: {
    color: 'text-black',
    backgroud: 'bg-amber-500',
    shadow: 'shadow-md shadow-amber-500/20',
    hover: 'hover:shadow-lg hover:shadow-amber-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  yellow: {
    color: 'text-black',
    backgroud: 'bg-yellow-500',
    shadow: 'shadow-md shadow-yellow-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-yellow-500/40',
  },
  lime: {
    color: 'text-black',
    backgroud: 'bg-lime-500',
    shadow: 'shadow-md shadow-lime-500/20',
    hover: 'hover:shadow-lg hover:shadow-lime-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  'light-green': {
    color: 'text-white',
    backgroud: 'bg-light-green-500',
    shadow: 'shadow-md shadow-light-green-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-light-green-500/40',
  },
  green: {
    color: 'text-white',
    backgroud: 'bg-green-500',
    shadow: 'shadow-md shadow-green-500/20',
    hover: 'hover:shadow-lg hover:shadow-green-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  teal: {
    color: 'text-white',
    backgroud: 'bg-teal-500',
    shadow: 'shadow-md shadow-teal-500/20',
    hover: 'hover:shadow-lg hover:shadow-teal-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  cyan: {
    color: 'text-white',
    backgroud: 'bg-cyan-500',
    shadow: 'shadow-md shadow-cyan-500/20',
    hover: 'hover:shadow-lg hover:shadow-cyan-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  'light-blue': {
    color: 'text-white',
    backgroud: 'bg-light-blue-500',
    shadow: 'shadow-md shadow-light-blue-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-light-blue-500/40',
  },
  blue: {
    color: 'text-white',
    backgroud: 'bg-blue-500',
    shadow: 'shadow-md shadow-blue-500/20',
    hover: 'hover:shadow-lg hover:shadow-blue-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  indigo: {
    color: 'text-white',
    backgroud: 'bg-indigo-500',
    shadow: 'shadow-md shadow-indigo-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-indigo-500/40',
  },
  'deep-purple': {
    color: 'text-white',
    backgroud: 'bg-deep-purple-500',
    shadow: 'shadow-md shadow-deep-purple-500/20',
    active: 'active:opacity-[0.85] active:shadow-none',
    hover: 'hover:shadow-lg hover:shadow-deep-purple-500/40',
  },
  purple: {
    color: 'text-white',
    backgroud: 'bg-purple-500',
    shadow: 'shadow-md shadow-purple-500/20',
    hover: 'hover:shadow-lg hover:shadow-purple-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  pink: {
    color: 'text-white',
    backgroud: 'bg-pink-500',
    shadow: 'shadow-md shadow-pink-500/20',
    hover: 'hover:shadow-lg hover:shadow-pink-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
  red: {
    color: 'text-white',
    backgroud: 'bg-red-500',
    shadow: 'shadow-md shadow-red-500/20',
    hover: 'hover:shadow-lg hover:shadow-red-500/40',
    active: 'active:opacity-[0.85] active:shadow-none',
  },
};

export default buttonFilled;
